#!/bin/sh -e
DIRNAME="$(dirname "$0")"

# utility functions
. "$DIRNAME"/functions.sh


# if a python project's top-level package
# is named differently from the project name
# override it in project_settings.sh
if [ -n "$ROOT_PACKAGE_NAME" ];
then
    package_name="$ROOT_PACKAGE_NAME"
else
    package_name="$(project_name)"
fi

proj_ver="$(current_version)"
if [ -f "$package_name"/__about__.py ];
then
    git commit -m "bump version to $proj_ver" "$package_name"/__about__.py
else
    quit "No '$package_name/__about__.py' found to commit" 1
fi
